shf/urls.py
from django.urls import path
from . import views

app_name = 'shf'

urlpatterns = [
    path('', views.search, name="search"),
    path('area/<int:pk>/', views.AreaDetailView.as_view(), name="area"),
    path('hotel/<int:pk>/', views.HotelDetailView.as_view(), name='hotel')
]

shf_last/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shf/', include('shf.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shf/models.py
from django.db import models


class Stadium(models.Model):
    stadium = models.CharField(max_length=50)

    def __str__(self):
        return self.stadium


class Condition(models.Model):
    CONDITIONS = (
        (1, "Shopping"),
        (2, "Amusement Facilities"),
        (3, "Hot Spring"),
        (4, "Japanese Culture Experience"),
        (5, "Food"),
        (6, "Amusement Park"),
        (7, "Landscape"),
    )
    condition = models.IntegerField(
        choices=CONDITIONS
    )

    def __str__(self):
        return self.get_condition_display()


class Fee(models.Model):
    FEES = (
        (1, "~Ten thousand"),
        (2, "Ten~Twenty thousand"),
        (3, "Twenty~Thirty thousand"),
        (4, "Thirty~Forty thousand"),
        (5, "Forty~Fifty thousand"),
        (6, "Fifty thousand ~"),
    )
    fee = models.IntegerField(
        choices=FEES
    )

    def __str__(self):
        return self.get_fee_display()


class Area(models.Model):
    area = models.CharField(max_length=10)
    stadium = models.ManyToManyField(Stadium)
    condition = models.ManyToManyField(Condition)
    fee = models.ManyToManyField(Fee)
    image = models.ImageField(upload_to='shf/', blank=True, null=True)
    image1 = models.ImageField(upload_to='shf/', blank=True, null=True)
    image2 = models.ImageField(upload_to='shf/', blank=True, null=True)
    spot1 = models.URLField(max_length=500, default="")
    spot2 = models.URLField(max_length=500, default="")
    spot_name1 = models.CharField(max_length=30, default="")
    spot_name2 = models.CharField(max_length=30, default="")
    desc1 = models.TextField(default="")
    desc2 = models.TextField(default="")

    def __str__(self):
        return self.area


class Hotel(models.Model):
    name = models.CharField(max_length=100)
    area = models.ManyToManyField(Area)
    condition = models.ManyToManyField(Condition)
    fee = models.IntegerField(default=0)
    detail = models.TextField()
    image1 = models.ImageField(upload_to='shf/', blank=True, null=True)
    image2 = models.ImageField(upload_to='shf/', blank=True, null=True)
    image3 = models.ImageField(upload_to='shf/', blank=True, null=True)
    access = models.TextField()
    booking = models.URLField(max_length=500)

    def __str__(self):
        return self.name

shf/forms.py
from django import forms
from . import models


class SearchForm(forms.Form):
    stadium = forms.ModelChoiceField(queryset=models.Stadium.objects,
                                     label='Stadium',
                                     empty_label='(Select From Here)',
                                     help_text='Select your venue what you watch the competition.',
                                     required=True
                                     )

    fee = forms.ChoiceField(choices=models.Fee.FEES,
                            label='Price',
                            widget=forms.RadioSelect,
                            help_text='You can choose only one.',
                            required=True
                            )

    condition = forms.MultipleChoiceField(choices=models.Condition.CONDITIONS,
                                          label='Condition',
                                          widget=forms.CheckboxSelectMultiple,
                                          help_text='The conditions you want for your staying area'
                                                    '(multiple choice allowed).',
                                          required=True
                                          )

shf/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import SearchForm
from . import models
from django.views.generic import DetailView


def search(request):
    form = SearchForm(request.GET)
    if form.is_valid():
        stadium = form.cleaned_data['stadium']
        fee = form.cleaned_data['fee']
        condition = form.cleaned_data['condition']
        area_list = models.Area.objects.filter(stadium=stadium, fee=fee, condition=condition[0])
        for i in range(1, len(condition)):
            area_list = area_list.filter(condition=condition[i])
        context = {'area_list': area_list}
        return render(request, 'shf/result.html', context)
    else:
        form = SearchForm()
    context = {'search_form': form}
    return render(request, 'shf/top.html', context)


class AreaDetailView(DetailView):
    model = models.Area
    template_name = 'shf/area.html'


class HotelDetailView(DetailView):
    model = models.Hotel
    template_name = 'shf/hotel.html'

shf/templates/shf/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Suburb Hotel Finder</title>
    <!-- Bootstrap CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color:#00608d;">
        <a class="navbar-brand" href={% url 'shf:search'%}>Suburb Hotel Finder</a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false"
            aria-label="ナビゲーションの切替">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="Navber">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'shf:search'%}">Top Page</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </nav>
    {% block content %}
    {% endblock %}

    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="{% static "shf/js/plugins/responsive-paginate.js" %}"></script>
</body>

</html>

shf/templates/shf/_pagination.html
{% load item_extras %}
<ul class="pagination">
    {% if page_obj.has_previous %}
        <li class="page-item pagination-prev">
            <a class="page-link" href="?{% url_replace request 'page' page_obj.previous_page_number %}">&laquo;</a>
        </li>
    {% else %}
        <li class="disabled page-item pagination-next">
            <span class="page-link">&laquo;</span>
        </li>
    {% endif %}
    {% for page in page_obj.paginator.page_range %}
        {% if page %}
            {% ifequal page page_obj.number %}
                <li class="active page-item">
                    <span class="page-link">{{ page }}
                        <span class="page-link sr-only">(current)</span>
                    </span>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" href="?{% url_replace request 'page' page %}">{{ page }}</a>
                </li>
            {% endifequal %}
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <li class="page-item pagination-next">
            <a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}">&raquo;</a>
        </li>
    {% else %}
        <li class="disabled page-item pagination-next">
            <span class="page-link ">&raquo;</span>
        </li>
    {% endif %}
</ul>

shf/templates/shf/area.html
{% extends "shf/_base.html" %}
{% block content%}
    <div class="container">
        <h1     class="text-center">{{ area.area }}</h1>
        <hr>
        <div class="row">
            <div class="col-3">
                <a href="{{ area.spot1 }}"><img src="{{ area.image1.url }}" alt="写真1" class="img-fluid"/></a>
            </div>
            <div class="col-9">
                <h5>{{ area.spot_name1 }}</h5>
                {{ area.desc1 }}
            </div>
        </div>
        <div class="row">
            <div class="col-3">
                <a href="{{ area.spot2 }}"><img src="{{ area.image2.url }}" alt="写真2" class="img-fluid" /></a>
            </div>
            <div class="col-9">
                <h5>{{ area.spot_name2 }}</h5>
                <p>{{ area.desc2 }}</p>
            </div>
        </div>
        <hr>
        <h2 class="text-center">Hotel</h2>
        {% for hotel in area.hotel_set.all%}
            <div class="card">
            <div class="row">
                <div class="col-3">
                    <a href="{% url 'shf:hotel' hotel.pk %}"><img src="{{ hotel.image1.url }}" alt="写真3" class="img-fluid" /></a>
                </div>
                <div class="col-9">
                    <a href="{% url 'shf:hotel' hotel.pk %}"><h5>{{ hotel.name }}</h5></a>
                    {% for condition in hotel.condition.all %}
                        <p>Genre: {{ condition }}</p>
                    {% endfor %}
                        <p>Fee: {{ hotel.fee }}~ / person</p>
                </div>
            </div>
        {% endfor %}
    </div>
    </div>
{% endblock %}

shf/templates/shf/hotel.html
{% extends "shf/_base.html" %}
{% block content%}
    <div class="container">
    <br>
    <h2>{{ hotel.name }}</h2>
        <hr     color="black">
        <div class="row d-block mx-auto" style="position:relative; left:40px">
            <img src="{{ hotel.image1.url }}" width="340" height="205" alt="写真1"/>
            <img src="{{ hotel.image2.url }}" width="340" height="205" alt="写真2"/>
            <img src="{{ hotel.image3.url }}" width="340" height="205" alt="写真3"/>
        </div>
        <div class="row" id="fonter">
            <div class="col-12">
                <h4>{{ hotel.detail | linebreaksbr }}</h4>
            </div>
        </div>
        <div class="card">
        <div>
            <h5><span class="mgr-10">　　　Access:{{ hotel.access | linebreaksbr}}</span></h5>
        </div>
        <div>
            <h5>　　　 Booking:<a href="{{ hotel.booking }}">Here</a>(May only support Japanese)</h5>
        </div>
        </div>
    </div>
{% endblock %}

shf/templates/shf/result.html
{% extends "shf/_base.html" %}
{% block content%}
    <h2 class="text-center">Our Recommended Sightseeing Area for You</h2>
    <div class="row jumbotron">
        <div class="col-12">
            <ul class="list-group">
            {% for area in area_list %}
                <img src="{{ area.image.url }}" alt="area" class="img-thumbnail"/>
                <li class="list-group-item">
                    <div class="row">
                        <div class="col-md-3">
                            <p>Area</p>
                        </div>
                        <div class="col-md-9">
                            <p>{{ area.area }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3">
                            <p>Genre</p>
                        </div>
                        <div class="col-9">
                            {% for condition in area.condition.all %}
                                {{ condition }},　
                            {% endfor %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <div class="float-right">
                                <a class="btn btn-outline-secondary " href="{% url 'shf:area' area.pk %}">Detail</a>
                            </div>
                        </div>
                    </div>
                </li>
                {% empty %}
                <li class="list-group-item">
                    No areas match your search criteria
                </li>
                {% endfor %}
            </ul>
            <div class="row" >
                <div class="col-12">
                    <div class="float-right">
                    {% include "shf/_pagination.html" %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

shf/templates/shf/top.html
{% extends "shf/_base.html" %}
{% block content %}
<h2 class="text-center" style="font-family: 'Arial Black', sans-serif">Suburb Hotel Finder</h2>
    <div class="jumbotron" style="background-color: white">
<form method="get">
    {{ search_form.non_field_errors }}
    {% for field in search_form %}
        <div class="form-control">
            {{ field.label_tag }}
            {% if field.label == "Price" %}
                {% for fee in field %}
                    {{ fee }}
                {% endfor %}
                <p style="opacity: 0.6">*{{ field.help_text }}</p>
            {% elif field.label == "Condition" %}
                {% for condition in field %}
                    {{ condition }}
                {% endfor %}
                <p style="opacity: 0.6">*{{ field.help_text }}</p>
            {% else %}
                {{ field }}
                <p style="opacity: 0.6">*{{ field.help_text }}</p>
            {% endif %}
        </div>
    {% endfor %}
    <div class="text-center"><input class="btn btn-lg btn-block btn-warning" type="submit" value="Search" style="color: #138496"></div>
</form>
    </div>
{% endblock %}